#!/usr/bin/env bash
# Regenerate docs/tool-reference.md from the tools the robot is actually serving, so the
# documentation cannot drift from the code. Needs a reachable robot (STACKCHAN_HOST).
#   STACKCHAN_HOST=<robot-ip> scripts/dump-tools.sh
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/.." && pwd)
OUT=${1:-$ROOT/docs/tool-reference.md}

"$ROOT/scripts/mcp.sh" '{"jsonrpc":"2.0","id":1,"method":"tools/list"}' | python3 -c '
import datetime
import json
import sys

data = json.load(sys.stdin)
if "result" not in data:
    sys.exit("unexpected response: " + json.dumps(data)[:200])
tools = sorted(data["result"]["tools"], key=lambda tool: tool["name"])

out = ["<!-- Generated by scripts/dump-tools.sh from a live robot. Do not edit by hand. -->", ""]
out.append("# Tool reference")
out.append("")
out.append("{} tools, read from a robot on {}.".format(len(tools), datetime.date.today().isoformat()))
out.append("")
for tool in tools:
    out.append("## `{}`".format(tool["name"]))
    out.append("")
    out.append(tool.get("description", "").strip())
    out.append("")
    schema = tool.get("inputSchema") or {}
    properties = schema.get("properties") or {}
    if not properties:
        out.append("No arguments.")
        out.append("")
        continue
    required = set(schema.get("required") or [])
    out.append("| Argument | Type | Required | Description |")
    out.append("|---|---|---|---|")
    for name, spec in properties.items():
        kind = spec.get("type", "")
        if spec.get("enum"):
            kind += " (" + ", ".join(str(value) for value in spec["enum"]) + ")"
        mark = "yes" if name in required else "no"
        description = (spec.get("description") or "").replace("|", "\\|")
        out.append("| `{}` | {} | {} | {} |".format(name, kind, mark, description))
    out.append("")
print("\n".join(out))
' > "$OUT"
echo "wrote $OUT"
